[package]
name = "tts-helper"
version = "0.1.0"
description = "An application to help streamers manage TTS events."
authors = ["Dylan Warren (https://github.com/Uhuh)"]
license = ""
repository = ""
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
# Tauri
tauri = { workspace = true, features = ["shell-open", "updater"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
tauri-plugin-playback = { path = "../plugins/tauri-plugin-playback" }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Audio
rodio = { workspace = true }
tts-helper-audio = { path = "../lib-backend/tts-helper-audio" }

# Web
tokio = { version = "1", features = ["rt"] }
axum = { version = "0.6", default-features = false, features = [
    "http1",
    "tokio",
    "tracing",
] }
reqwest = { workspace = true, features = ["json"] }
bytes = { workspace = true }

# Errors
anyhow = { workspace = true }
thiserror = { workspace = true }

# Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# Util
crossbeam = { workspace = true }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
