[workspace]
resolver = "2"
members = ["src-tauri", "plugins/*", "lib-backend/*"]

[workspace.dependencies]
# Tauri
tauri = "2.0.0-beta.10"
tauri-build = "2.0.0-beta.8"
tauri-plugin = "2.0.0-beta.8"
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-window-state = "2.0.0-beta.2"
tauri-plugin-cli = "2.0.0-beta.2"
tauri-plugin-dialog = "2.0.0-beta.2"
tauri-plugin-updater = "2.0.0-beta.2"
tauri-plugin-http = { version = "2.0.0-beta.2", features = ["native-tls"] }
tauri-plugin-app = "2.0.0-alpha.2"
tauri-plugin-shell = "2.0.0-beta.2"
tauri-plugin-devtools = { git = "https://github.com/crabnebula-dev/devtools", version = "2.0.0-beta.0" }

# Serialization
serde = "1"
serde_with = "3"
serde_json = "1"

# Audio
rodio = "0.17"

# Web
bytes = "1"

# Errors
anyhow = "1"
thiserror = "1"

# Tracing
tracing = "0.1"
tracing-subscriber = "0.3"

# Utility
crossbeam = "0.8"
static_assertions = "1"
